### ISSUE TITLE
How to extract firmware with Quartus Programmer?

### ISSUE THREAD

**Issue by luyi1888** [ruurdk/storey-peak#1]
I followed your step described in firmware/README.md.
The README.md says the Quartus will program the FPGA with a default flashloader IP. But in my case, it seems not.

I got the following message from log window.
Error (209062): Flash Loader IP not loaded on device 1
Error (209012): Operation failed

What did I miss?
I am using the USB-Blaster II download cable(clone) connects to J5 header.  I can use this method to program the FPGA with simple LED blinky.
And LED is turn on then off when the card is power-on. So the QSPI Flash/Factory Firmware should be ok.

Thanks.

**Comment by luyi1888** [comment]
In case anyone needs J5 header pinout.
| PIN | Usage |
|--|--|
|1|TCK|
|2|GND|
|3|TDO|
|4|2V5/VREF/VCC|
|5|TMS|
|6|2V5/VREF/VCC|
|7|TDI|
|8|GND|

**Comment by luyi1888** [comment]
solved by myself.
convert sof to jic format.  Make config in Active Serial mode.

**Comment by MauroFoti** [comment]
> solved by myself. convert sof to jic format. Make config in Active Serial mode.

Hello, I'm having the same problem as you do while trying to dump the firmware, but I don't understand your solution. Did you use an external programmer or the integrated USB port?

**Comment by luyi1888** [comment]
> > solved by myself. convert sof to jic format. Make config in Active Serial mode.
> 
> Hello, I'm having the same problem as you do while trying to dump the firmware, but I don't understand your solution. Did you use an external programmer or the integrated USB port?

I'm using external programmer(usb-blaster ii clone). But it should be ok for integrated one.

Step1:

![Image](https://github.com/user-attachments/assets/c92aa5b7-550a-4aba-95df-47477d5a1454)

Step2:

![Image](https://github.com/user-attachments/assets/6f3d4048-9de6-44ec-9987-10884ca61dfa)

Step3:

![Image](https://github.com/user-attachments/assets/12f43303-24c8-40ab-be62-c3c39da63015)

**Comment by MauroFoti** [comment]
I followed the same steps as you did, even changed the fpga and flash devices as yours, but I still fail with the same error message.

Since I don't have (yet) a programmer with the smaller connector on this board, I'm forced to use the built-in programmer for now. I followed the guide on this repository for compiling the driver needed by quartus, but maybe it's not working correctly. Have you ever tried with the builtin programmer?

![Image](https://github.com/user-attachments/assets/b2b627b1-90eb-42b2-ab3d-c77b43534c32)

**Comment by luyi1888** [comment]
I'm not open programmer from quartus. I start it standalone. It should be some difference.

Follow this, If you want it work from quartus.
create jic file first.
then open jic file in programmer, so you can flash your bitsream or dump flash content.

![Image](https://github.com/user-attachments/assets/55966637-76f0-4134-b43b-1818db0d7f21)

**Comment by luyi1888** [comment]
forgot it.
better to choose "Active Serial x4"
